const PUJA_RADIO_TRACKS = [
  {id:"SFJeglBF5cg",title:"Dugga Elo",artist:"Monali Thakur",dur:"2:27"},
  {id:"HeF8UhOYnq0",title:"Dugga Ma",artist:"Arijit Singh",dur:"4:31"},
  {id:"S8WKJt7bWGg",title:"Ebar Jeno Onno Rokom Pujo",artist:"Nakash Aziz Official",dur:"3:33"},
  {id:"7uzjfZ423Kc",title:"Dhak Baja Kashor Baja",artist:"Shreya Ghoshal Official",dur:"4:26"},
  {id:"cAD7KutMTJw",title:"Bolo Dugga Elo",artist:"Kaushik-Guddu",dur:"3:20"},
  {id:"w6SQsKD2U-Y",title:"Aamaar Dugga",artist:"Monali Thakur",dur:"3:20"},
  {id:"PqdxxIAgjgk",title:"Dhaker Taley",artist:"Release",dur:"4:43"},
  {id:"G65AupY9ge0",title:"Dugga Elo",artist:"Akriti Kakar",dur:"3:58"},
  {id:"zSqRknvFD_s",title:"Shundori Komola",artist:"Release",dur:"3:14"},
  {id:"RB_5ED6GIao",title:"Elo Je Maa",artist:"Abhijeet Unplugged",dur:"5:08"},
  {id:"upYGF3YAHeo",title:"O Menoka O Menoka",artist:"ANTARA NANDY",dur:"3:16"},
  {id:"p_hqO0sJh-I",title:"Ailo Uma Barite",artist:"ANTARA NANDY",dur:"3:53"},
  {id:"x_Nar1eYzBM",title:"Uma Ashe Notun Saje",artist:"Ankita Bhattacharyya",dur:"3:06"},
  {id:"I5uMBp5wDhI",title:"Abar Elo Maa",artist:"Rahul Dutta",dur:"3:07"},
  {id:"CWtqPoZrUoA",title:"Joy Joy Durga Ma",artist:"Agnibha Bandyopadhyay",dur:"5:51"},
  {id:"uLSEEBGr4Ag",title:"Durga Maa",artist:"Akassh",dur:"3:41"},
  {id:"W-YAf-bHkCw",title:"Gouri Elo Dekhe Jalo",artist:"DOHAR FOLK",dur:"5:40"},
  {id:"JOQdF0wRjYY",title:"Dhak Baaja Komor Nacha",artist:"Release",dur:"3:33"},
  {id:"Ku7mJminJxI",title:"Durge Durge Durgatinashini",artist:"Asha Bhosle",dur:"5:10"},
  {id:"z-T4qiQMXaw",title:"Rupang Dehi",artist:"Snita Pramanik Ghosh",dur:"4:18"},
  {id:"1Yycc3tejNw",title:"Aigiri Nandini",artist:"Rajalakshmee Sanjay Official",dur:"15:02"},
  {id:"nLrpLXaWbxk",title:"Baja Sanai Aar Baja Re Dhol",artist:"Abhijeet Unplugged",dur:"4:44"},
  {id:"RB_5ED6GIao",title:"Elo Je Maa",artist:"Abhijeet Unplugged",dur:"5:08"},
  {id:"ZusnukjtotQ",title:"Maa Ashchhe (From \"Maa Ashchhe\")",artist:"Sanjeev Tiwari",dur:"3:27"},
  {id:"hDve9YmTZq4",title:"Esho Maa Durga",artist:"Shamik Guha Roy",dur:"3:57"},
  {id:"8z-SSVEj9o8",title:"Maa Go Tui",artist:"Somchanda Bhattacharya",dur:"2:00"},
  {id:"sto9TBxGibE",title:"Jago Uma",artist:"Rupankar",dur:"5:18"},
  {id:"mXqUIFUYqpM",title:"Aigiri Nandini (feat. Samarthan, Ramprakash) (Rock Version)",artist:"Sowrabha",dur:"4:57"},
  {id:"p_hqO0sJh-I",title:"Ailo Uma Barite",artist:"ANTARA NANDY",dur:"3:53"},
  {id:"UpeueoYgHnE",title:"Aaj Baaje",artist:"Somchanda Bhattacharya",dur:"3:34"},
  {id:"-vPbyevbN4k",title:"Yoddhar Saathe Ebar Pujo Katan",artist:"Nakash Aziz Official",dur:"3:47"},
  {id:"9fG229zIL_0",title:"Pujo Pujo Gondho",artist:"Anupam Roy",dur:"2:47"},
  {id:"E40N8rKKTCc",title:"Pujor Dhaak Theme",artist:"SUROBAIBHAB ( Bibhabendu Bhattacharya Official)",dur:"1:31"},
  {id:"fpuadv59iYw",title:"Jaago Uma",artist:"Anupam Roy",dur:"5:18"},
  {id:"srJlx60zfBQ",title:"Pujor Gaan",artist:"Poushali Bhattacharya",dur:"4:45"},
  {id:"w6SQsKD2U-Y",title:"Aamaar Dugga",artist:"Monali Thakur",dur:"3:20"},
  {id:"jwMo3vrsL7s",title:"Gouri Elo (From \"Raktabeej\")",artist:"DOHAR FOLK",dur:"3:57"},
  {id:"nH65Xk8kPjQ",title:"Aham Rudre",artist:"Release",dur:"2:39"},
  {id:"YNxK-eLJmro",title:"Elo Re Pujo Elo",artist:"Dabbu",dur:"3:13"},
  {id:"Rx7l8bjzjg4",title:"Chaarpashe Aalo Hok",artist:"Release",dur:"11:34"},
  {id:"CYcqPK0Dl60",title:"O Thakur",artist:"Upal Sengupta",dur:"2:54"},
  {id:"PEiFJAy_zsM",title:"Shubho Shubho",artist:"Altamash Faridi",dur:"3:14"},
  {id:"YnU9c1aj5hY",title:"He Maa Durga Maa",artist:"Aseema Panda",dur:"5:12"},
  {id:"VNI_XEx7z-g",title:"Durga Maa Eseche",artist:"Akassh",dur:"3:07"},
  {id:"avySoa5OW1w",title:"Eseche Maa Durga Maa - (DJ Remix)",artist:"Keshab Dey",dur:"3:03"},
  {id:"hDukD5TJmV4",title:"Kolki",artist:"Monami Ghosh",dur:"4:05"},
  {id:"LLer3VPOcxg",title:"Dugga Ma Asche",artist:"Infra",dur:"3:34"},
  {id:"BvIcx9ev8X0",title:"Debi Sajer Gaan",artist:"Rupak Tiary",dur:"3:01"},
  {id:"ny3oWUnm2Mk",title:"Tomake Chai",artist:"Arijit Singh",dur:"4:14"},
  {id:"j9_MLElmS9g",title:"Meri Maa Ke Barabar Koi Nahi",artist:"Jubin Nautiyal",dur:"4:59"},
  {id:"SFJeglBF5cg",title:"Dugga Elo",artist:"Monali Thakur",dur:"2:27"},
  {id:"cFsCf0MGuuA",title:"Bajlo Tomar Aalor Benu",artist:"Release",dur:"5:16"},
  {id:"63X0l49OyjI",title:"Durge Durge Durgatinashini",artist:"Release",dur:"3:43"},
  {id:"_GUdZJQun2I",title:"Madhukaitava Vidhwangsi",artist:"Tushar Dutta",dur:"9:49"},
  {id:"QvhNGDZhJvE",title:"Kalo Jole Kuchla Tole",artist:"IMAN",dur:"4:23"},
  {id:"j7nWykTLEMs",title:"Bajlo Tomar Alor Benu",artist:"Sriparna Das",dur:"4:44"},
  {id:"cFsCf0MGuuA",title:"Bajlo Tomar Aalor Benu",artist:"Release",dur:"5:16"},
  {id:"DxaNt-pmObM",title:"Bajlo Tomar Aalor Benu With Narration",artist:"Supriti Ghosh",dur:"4:24"},
  {id:"wLVkrgkoPro",title:"Mahishasura Mardhini",artist:"Release",dur:"5:53"},
  {id:"6ZCfPaz28_U",title:"Ya Chandi",artist:"Chorus",dur:"1:37"},
  {id:"YC4ERU01ZxY",title:"Jago Tumi Jago",artist:"Trissha Chatterjee",dur:"2:29"},
  {id:"Z7kpAzbC66E",title:"Borondala Saaja",artist:"Madhuraa Bhattacharya",dur:"2:41"},
  {id:"43_oBh4YsQs",title:"Phagun Haoyay Haoyay (From \"Bhalobashar Bari\")",artist:"Jayati Chakraborty",dur:"2:35"},
  {id:"_RmN29SHVS8",title:"Ogo Amar Agamani-alo",artist:"Sipra Basu",dur:"3:20"},
  {id:"aNPO5geLn_E",title:"Raai Jago Go",artist:"Pousali Banerjee",dur:"6:00"},
  {id:"z-T4qiQMXaw",title:"Rupang Dehi",artist:"Snita Pramanik Ghosh",dur:"4:18"},
  {id:"PRTXLKCV6Nk",title:"ওগো আমার আগমনী আলো",artist:"Samadrita Ghosh",dur:"4:51"},
  {id:"gbGVjyHq8iA",title:"Durge Durge Durgatinashini",artist:"Asha Bhosle",dur:"5:10"},
  {id:"ocCQ1UVsel8",title:"Agomonir Gaan",artist:"Anupam Roy",dur:"5:47"},
  {id:"707QgEnx8Hs",title:"Saajan Rock the Dotara (Folk - Bandish Mix)",artist:"Timir Biswas Studio",dur:"4:28"},
  {id:"d-NMikRHMQQ",title:"Pujar Gaan (From \"Hooligaanism\")",artist:"Hooligaanism",dur:"6:33"},
  {id:"WM0waOKjzkE",title:"Asatoma Sadgamaya",artist:"Arijit Singh",dur:"3:07"},
  {id:"ADpMft-PUb8",title:"Gouri Elo",artist:"Aritra Dasgupta",dur:"5:35"},
  {id:"S-XOArX0faE",title:"Doob De Re Mon",artist:"Nirmalya Roy",dur:"2:16"},
  {id:"aJBZvnbS9vM",title:"Apur Paayer Chhaap",artist:"Arijit Singh",dur:"4:06"},
  {id:"AFOg5wPxduc",title:"Esho Hey",artist:"Release",dur:"5:54"},
  {id:"jkCWHTt2ml4",title:"Laage Ura Dhura (From \"Toofan\")",artist:"Pritom Hasan",dur:"3:14"},
  {id:"VUl071_Qw6E",title:"Bholey Baba",artist:"Release",dur:"4:30"},
  {id:"NwjbjGQXkdU",title:"Dushtu Kokil",artist:"KONA",dur:"3:31"},
  {id:"G2tTYmSzR6U",title:"Mala Re",artist:"JEET GANNGULI OFFICIAL",dur:"4:08"},
  {id:"_QpaZZzXCiQ",title:"Koka Kola",artist:"Samidh Mukherjee",dur:"5:00"},
  {id:"8xtWhxDvq7s",title:"Michhrir Dana",artist:"Shreya Ghoshal Official",dur:"3:34"},
  {id:"QL6chT20jz8",title:"Desi Chhori",artist:"Release",dur:"3:49"},
  {id:"IFkARpGk8FA",title:"Party Shoes",artist:"Release",dur:"3:46"},
  {id:"tMD3VtUyGz8",title:"Bujhina Toh Tai",artist:"Nusraat Faria",dur:"3:05"},
  {id:"eoLZVAk9t_U",title:"Lady Killer Romeo",artist:"JEET GANNGULI OFFICIAL",dur:"3:47"},
  {id:"qrCDBZZ_SxM",title:"Police Chorer Preme Porechhe",artist:"Jeet Gannguli",dur:"4:16"},
  {id:"4vrS8JUUkQA",title:"Baundule Ghuri",artist:"Anupam Roy",dur:"5:44"},
  {id:"f9FX9_MN-G4",title:"Tumi Jantei Paro Naa",artist:"Mahtim Shakib",dur:"3:45"},
  {id:"zCj_U2nc_Hk",title:"Taakey Olpo Kachhe Dakchhi",artist:"Mahtim Shakib",dur:"3:15"},
  {id:"Ev1NLm7Kd4g",title:"Egiye De",artist:"Release",dur:"4:14"},
  {id:"y6g8eSP0MB0",title:"Shudhu Tomari Jonyo Theme",artist:"Arijit Singh",dur:"3:17"},
  {id:"9yxSXBjT8jg",title:"Amake Nao",artist:"Debayan Banerjee",dur:"3:10"},
  {id:"55lHMJ4OnMo",title:"Sajani (From Dilkhush)",artist:"Nilayan Chatterjee",dur:"3:28"},
  {id:"lan_A5i_JwY",title:"Pheshey Jaai",artist:"Release",dur:"4:11"},
  {id:"tDolwm2f9g0",title:"Ure Geche",artist:"Ash King",dur:"4:27"},
  {id:"IXgannYJ9mE",title:"Aashona",artist:"Arijit Singh",dur:"4:04"},
  {id:"yB5tJlDGQo4",title:"Era Sukher Laagi (From Chokher Bali)",artist:"Release",dur:"2:45"},
  {id:"4TmNBuJXpns",title:"Tumi Aashe Paashe",artist:"Nakash Aziz Official",dur:"4:22"},
  {id:"EVPIkFIVHCg",title:"Hey Shokha",artist:"Somlata Acharyya Chowdhury",dur:"4:24"},
  {id:"VF0T1YLzkEw",title:"Shaajo Shaajao (From \"Ballabhpurer Roopkotha\")",artist:"Release",dur:"4:33"},
  {id:"RQ1WrgD8vrA",title:"Notun Premer Gaan (From \"Ballabhpurer Roopkotha\")",artist:"Debraj Bhattacharya",dur:"3:50"},
  {id:"0-rIe6yzwGE",title:"Tumi Emni Emni Esho",artist:"Sanchita Bhowmick",dur:"3:37"},
  {id:"8NeUGOEpGh0",title:"Maa Go Tui",artist:"Shovan Ganguly Official",dur:"2:00"},
  {id:"a0ZwJJSlxC8",title:"Khoka Babu",artist:"Rishi",dur:"4:17"},
  {id:"Bx2avxFHwM0",title:"Pyaar Ka Bukhaar",artist:"Jeet Gannguli",dur:"3:34"},
  {id:"KqpIIaCJggY",title:"Ankhiyon Ke Jharokhon Se - Classic Romantic Song - Sachin & Ranjeeta - Old Hindi Songs",artist:"Rajshri",dur:"6:45"}
];